<a href="https://colab.research.google.com/github/dashy0070/Cybersecurity_AI/blob/main/NIDS_using_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Toy NIDS - Network Intrusion Detection System

Create dataset

In [ ]:
payload = [10,10,0,0,0,5,12]
protocol = ['TCP', 'UDP', 'TCP', 'UDP', 'UDP','UDP','UDP']
attack = ['N', 'N','Y','Y','Y','Y', 'N']

In [ ]:
#Business Objectives
#Data preparation
#model and eval
#Deploy the model

#Data preparartion
#Create a data frame using a payload protocol

In [2]:
import pandas as pd

payload = [10,10,0,0,0,5,12]
protocol = ['TCP', 'UDP', 'TCP', 'UDP', 'UDP','UDP','UDP']
attack = ['N', 'N','Y','Y','Y','Y', 'N']

data = {'Payload': payload, 'Protocol': protocol, 'Attack': attack}
df = pd.DataFrame(data)
display(df.head())

   Payload Protocol Attack
0       10      TCP      N
1       10      UDP      N
2        0      TCP      Y
3        0      UDP      Y
4        0      UDP      Y

#Inference : Data is loaded

Prompt: Create a new column called PLB and update the column with the rule if the payload is less than 9 call is '<9' else call it '>=9'

In [3]:
import numpy as np

df['PLB'] = np.where(df['Payload'] < 9, '<9', '>=9')
display(df.head())

   Payload Protocol Attack  PLB
0       10      TCP      N  >=9
1       10      UDP      N  >=9
2        0      TCP      Y   <9
3        0      UDP      Y   <9
4        0      UDP      Y   <9

[link text](https://)



---